window.PATTERN_ENCYCLOPEDIA = [
  {
    id: "strong-breakout-follow-through",
    title: "强突破 + 跟随",
    family: "突破",
    aliases: ["Strong BO", "Breakout with Follow-through"],
    winRate: "60-70%+",
    probScore: 70,
    importance: 100,
    difficulty: 3,
    diagram: "breakout",
    source: "PAF 15 Breakouts / HTT 41 Trading Breakouts / 10 Best Patterns",
    summary: "Brooks 体系里最重要的高概率顺势形态。关键不是突破那一根K，而是突破后有没有继续收在突破方向。",
    best: ["清晰支撑阻力、区间高低点或趋势线被突破", "突破K实体大，收盘靠近极端", "后续1-3根K没有立刻回到原区间"],
    entry: ["突破收盘后顺势入场", "等待第一次小回调或突破回踩入场", "强趋势日可用小仓位追随"],
    stop: ["突破K另一端", "突破回调结构外", "如果止损过远，用更小仓位或等待回调"],
    target: ["测量移动", "下一个磁力位", "至少先看1R，再根据跟随决定是否波段"],
    traps: ["区间中间的假突破", "高潮末端追单", "突破后没有跟随仍死扛"]
  },
  {
    id: "breakout-pullback",
    title: "突破回踩 / Breakout Pullback",
    family: "突破",
    aliases: ["BO PB", "突破测试", "旧阻力变支撑"],
    winRate: "60-65%",
    probScore: 65,
    importance: 98,
    difficulty: 2,
    diagram: "breakout",
    source: "PAF 15 Breakouts / PAF 19 Support and Resistance",
    summary: "突破成功后，市场回测突破点；如果回测不深且出现顺突破信号，说明被突破的价位开始反向支撑/阻力。",
    best: ["突破前价位明显", "突破后有跟随", "回踩不深，且没有强反向收盘"],
    entry: ["回踩突破点后顺突破方向入场", "用信号K高/低点触发", "强突破后第一次回调优先级最高"],
    stop: ["回踩低/高点外", "突破点另一侧", "信号K另一端"],
    target: ["突破测量目标", "趋势通道线", "前高/前低或当日磁力位"],
    traps: ["无跟随突破后硬等回踩", "回踩已经变成深回调", "突破点附近目标太近"]
  },
  {
    id: "gap-breakout",
    title: "缺口突破",
    family: "缺口",
    aliases: ["Breakaway Gap", "Gap BO"],
    winRate: "60-65%",
    probScore: 64,
    importance: 86,
    difficulty: 3,
    diagram: "breakout",
    source: "PAF 11 Gaps / PAF 15 Breakouts",
    summary: "缺口让市场快速重新定价。若缺口方向有跟随，常形成趋势日或测量移动背景。",
    best: ["开盘或盘中跳离关键价位", "缺口不被快速回补", "后续K线继续同方向收盘"],
    entry: ["缺口方向跟随后顺势", "第一次回踩缺口边缘失败后入场", "强趋势开盘可等小回调"],
    stop: ["缺口边缘另一侧", "回踩结构外", "开盘极端外"],
    target: ["测量缺口", "昨日高低点", "日内测量移动"],
    traps: ["把所有缺口都当趋势", "缺口快速回补仍追", "新闻跳空后止损过大"]
  },
  {
    id: "measuring-gap",
    title: "测量缺口",
    family: "缺口",
    aliases: ["Measuring Gap", "MM Gap"],
    winRate: "60%左右",
    probScore: 61,
    importance: 75,
    difficulty: 3,
    diagram: "measured",
    source: "PAF 11 Gaps / PAF 20 Measured Moves",
    summary: "趋势中段出现未回补缺口时，市场常把缺口当作中点，并尝试走出等距目标。",
    best: ["已有强趋势第一段", "缺口后仍有跟随", "回补失败"],
    entry: ["缺口方向回调失败后顺势", "突破回踩成功后入场", "不单独因缺口入场"],
    stop: ["缺口另一侧", "最近回调结构外"],
    target: ["用缺口投射测量移动", "前一段等距目标", "下一个磁力位"],
    traps: ["目标位附近追单", "把衰竭缺口误判成测量缺口", "忽略缺口快速回补"]
  },
  {
    id: "high-2-bull-flag",
    title: "High 2 多头旗",
    family: "回调",
    aliases: ["H2", "Two-legged Pullback"],
    winRate: "60%左右",
    probScore: 62,
    importance: 96,
    difficulty: 2,
    diagram: "h2l2",
    source: "PAF 09 Pullbacks and Bar Counting / 10 Best Patterns",
    summary: "上涨趋势里两段回调失败后，多头重新接管。重点是趋势背景，不是机械数到2。",
    best: ["Always In Long 清晰", "回调两段但没有破坏趋势", "第二次上破信号K质量好"],
    entry: ["第二次向上触发买入", "信号K高点上方买入", "强趋势中可用小止损回调买"],
    stop: ["回调低点下方", "信号K下方", "若回调太深则放弃"],
    target: ["前高", "测量移动", "通道线或磁力位"],
    traps: ["交易区间中间硬数H2", "趋势已经坏掉仍买", "信号K太大导致风险收益差"]
  },
  {
    id: "low-2-bear-flag",
    title: "Low 2 空头旗",
    family: "回调",
    aliases: ["L2", "Two-legged Pullback"],
    winRate: "60%左右",
    probScore: 62,
    importance: 96,
    difficulty: 2,
    diagram: "h2l2",
    source: "PAF 09 Pullbacks and Bar Counting / 10 Best Patterns",
    summary: "下跌趋势里两段反弹失败后，空头重新接管。它是最常用的顺趋势回调形态之一。",
    best: ["Always In Short 清晰", "反弹两段但没有形成强多头跟随", "第二次下破信号K质量好"],
    entry: ["第二次向下触发卖出", "信号K低点下方卖出", "强空头趋势中反弹卖"],
    stop: ["回调高点上方", "信号K上方", "若反弹突破趋势线并跟随则放弃"],
    target: ["前低", "测量移动", "通道线或下方磁力位"],
    traps: ["把区间中间波动当L2", "反弹已转多仍卖", "在支撑位上方空间不足"]
  },
  {
    id: "high-1-low-1",
    title: "High 1 / Low 1",
    family: "回调",
    aliases: ["H1", "L1", "一次回调"],
    winRate: "55-60%",
    probScore: 58,
    importance: 82,
    difficulty: 2,
    diagram: "trend",
    source: "PAF 09 Pullbacks and Bar Counting",
    summary: "强趋势中第一次小回调后的顺势触发。趋势越强，第一次回调越有价值；普通趋势里可能太早。",
    best: ["强突破后第一波浅回调", "趋势K连续收盘强", "逆势方没有形成两段运动"],
    entry: ["H1买入或L1卖出", "小回调结束时顺趋势入场"],
    stop: ["小回调结构外", "信号K另一端"],
    target: ["前高/前低", "测量移动", "趋势通道线"],
    traps: ["普通趋势中太早入场", "高潮后追第一回调", "在区间中间误用"]
  },
  {
    id: "high-3-low-3",
    title: "High 3 / Low 3",
    family: "回调",
    aliases: ["H3", "L3", "复杂回调"],
    winRate: "50-58%",
    probScore: 55,
    importance: 68,
    difficulty: 3,
    diagram: "h2l2",
    source: "PAF 09 Pullbacks and Bar Counting / Steven 复杂回调",
    summary: "趋势回调超过两次尝试，说明趋势已经不如强趋势干净；仍可顺势，但要降低预期。",
    best: ["趋势仍未被结构性破坏", "回调靠近均线或支撑阻力", "第三次触发有强信号K"],
    entry: ["第三次顺趋势触发", "等更强信号或突破微型趋势线"],
    stop: ["回调极端外", "信号K另一端"],
    target: ["前高/前低优先", "不要默认大波段"],
    traps: ["复杂回调其实已变交易区间", "过度数K", "目标设得太远"]
  },
  {
    id: "two-legged-pullback-to-ema",
    title: "两段回调到 EMA",
    family: "回调",
    aliases: ["TLP to EMA", "均线回调"],
    winRate: "58-62%",
    probScore: 60,
    importance: 90,
    difficulty: 2,
    diagram: "trend",
    source: "PAF 09 / PAF 14 Trends",
    summary: "趋势中的两段回调到20EMA附近，是 Brooks 课程里最常见的顺势入场背景。",
    best: ["趋势清晰且回调靠近EMA", "回调两段后出现顺势信号", "EMA附近没有被强力突破"],
    entry: ["顺趋势信号K触发", "微型趋势线突破后入场"],
    stop: ["回调极端外", "EMA另一侧结构外"],
    target: ["前高/前低", "测量移动", "趋势通道线"],
    traps: ["EMA被当成魔法线", "强反向突破后仍顺势", "区间里在EMA附近来回挨打"]
  },
  {
    id: "wedge-bull-flag",
    title: "楔形多头旗",
    family: "楔形",
    aliases: ["Wedge Bull Flag", "三推回调"],
    winRate: "58-62%",
    probScore: 60,
    importance: 88,
    difficulty: 3,
    diagram: "wedge",
    source: "PAF 24 Wedges / 10 Best Patterns",
    summary: "上涨趋势中的三推下跌回调。顺大趋势交易时，楔形旗形通常比逆势楔形反转更稳。",
    best: ["大背景仍是多头趋势", "三推回调到EMA、趋势线或支撑", "第三推失败并出现多头信号"],
    entry: ["第三推失败后买入", "突破回调微型趋势线后买入"],
    stop: ["第三推低点下方", "信号K下方"],
    target: ["前高", "两段上行", "测量移动"],
    traps: ["把主要反转误当多头旗", "第三推仍强跌却抢", "回调已经转成空头趋势"]
  },
  {
    id: "wedge-bear-flag",
    title: "楔形空头旗",
    family: "楔形",
    aliases: ["Wedge Bear Flag", "三推反弹"],
    winRate: "58-62%",
    probScore: 60,
    importance: 88,
    difficulty: 3,
    diagram: "wedge",
    source: "PAF 24 Wedges / 10 Best Patterns",
    summary: "下跌趋势中的三推反弹。第三推失败后，空头常重新控制。",
    best: ["大背景仍是空头趋势", "三推反弹到EMA、趋势线或阻力", "第三推失败并出现空头信号"],
    entry: ["第三推失败后卖出", "跌破微型趋势线后卖出"],
    stop: ["第三推高点上方", "信号K上方"],
    target: ["前低", "两段下行", "测量移动"],
    traps: ["把MTR底部误当空头旗", "反弹已经强突破仍卖", "支撑太近"]
  },
  {
    id: "micro-double-bottom-bull-flag",
    title: "微型双底多头旗",
    family: "双顶双底",
    aliases: ["Micro DB Bull Flag", "MDB"],
    winRate: "55-60%",
    probScore: 58,
    importance: 74,
    difficulty: 3,
    diagram: "range",
    source: "PAF 25 Double Tops and Bottoms",
    summary: "强上涨中的小级别双底回调。它表达空头两次尝试压低失败。",
    best: ["上涨趋势中", "两次小低点接近", "第二次测试后出现强多头收盘"],
    entry: ["第二个低点失败后买入", "突破微型颈线后买入"],
    stop: ["双底下方", "信号K下方"],
    target: ["前高", "小测量移动"],
    traps: ["位置在区间中间", "双底下破并跟随", "形态太小但止损太大"]
  },
  {
    id: "micro-double-top-bear-flag",
    title: "微型双顶空头旗",
    family: "双顶双底",
    aliases: ["Micro DT Bear Flag", "MDT"],
    winRate: "55-60%",
    probScore: 58,
    importance: 74,
    difficulty: 3,
    diagram: "range",
    source: "PAF 25 Double Tops and Bottoms",
    summary: "强下跌中的小级别双顶反弹。它表达多头两次尝试上攻失败。",
    best: ["下跌趋势中", "两次小高点接近", "第二次测试后出现强空头收盘"],
    entry: ["第二个高点失败后卖出", "跌破微型颈线后卖出"],
    stop: ["双顶上方", "信号K上方"],
    target: ["前低", "小测量移动"],
    traps: ["位置在区间中间", "双顶上破并跟随", "下方支撑太近"]
  },
  {
    id: "trading-range-failed-breakout",
    title: "交易区间失败突破",
    family: "交易区间",
    aliases: ["TR FBO", "Failed Breakout"],
    winRate: "55-60%",
    probScore: 60,
    importance: 96,
    difficulty: 3,
    diagram: "range",
    source: "PAF 18 Trading Ranges / HTT 47 Trading in Trading Ranges / Steven 11-12",
    summary: "区间里很多突破会失败。失败突破是 Brooks 交易区间逻辑的核心。",
    best: ["区间边缘", "突破后无跟随", "价格快速回到区间内"],
    entry: ["回到区间后反向入场", "第二次失败后更稳"],
    stop: ["突破极端外", "信号K另一端"],
    target: ["区间中线", "区间另一侧", "先小目标再看跟随"],
    traps: ["强趋势日逆势", "区间中间乱做", "突破还没失败就抢反向"]
  },
  {
    id: "buy-low-sell-high-range",
    title: "区间买低卖高",
    family: "交易区间",
    aliases: ["Buy Low Sell High", "BLSH"],
    winRate: "55-60%",
    probScore: 58,
    importance: 92,
    difficulty: 3,
    diagram: "range",
    source: "PAF 18 Trading Ranges / HTT 47",
    summary: "交易区间里，多空双方都能赚钱。高概率不是追随强K，而是在边缘等待失败和反向。",
    best: ["重叠多、尾巴多", "接近区间高低点", "目标到中线或另一侧仍有空间"],
    entry: ["区间低位买入", "区间高位卖出", "边缘失败突破后入场"],
    stop: ["区间边缘外", "失败突破极端外"],
    target: ["中线", "另一侧", "快速小目标"],
    traps: ["区间中间交易", "强突破时逆势", "目标按趋势日想太远"]
  },
  {
    id: "breakout-mode",
    title: "突破模式 / Breakout Mode",
    family: "交易区间",
    aliases: ["BOM", "Breakout Mode"],
    winRate: "等待方向后60%+",
    probScore: 57,
    importance: 86,
    difficulty: 3,
    diagram: "range",
    source: "PAF 18 Trading Ranges / PAF 26 Triangles",
    summary: "市场压缩后，多空都在等待突破。突破前方向不清，突破后跟随才给概率。",
    best: ["窄区间、三角形或反复收敛", "成交/波动压缩后突然扩张", "突破有强收盘和跟随"],
    entry: ["等待突破方向确认", "突破回踩成功后入场"],
    stop: ["突破前区间另一侧", "回踩结构外"],
    target: ["区间高度测量移动", "下一个磁力位"],
    traps: ["提前押方向", "第一次假突破就追", "窄区间里频繁止损"]
  },
  {
    id: "barb-wire-tight-range",
    title: "铁丝网窄区间",
    family: "交易区间",
    aliases: ["Barb Wire", "Tight Trading Range"],
    winRate: "不适合交易",
    probScore: 35,
    importance: 70,
    difficulty: 5,
    diagram: "range",
    source: "PAF 18 Trading Ranges",
    summary: "多根K线重叠、尾巴多、方向反复，是最容易让新手来回挨打的结构。",
    best: ["识别后少交易", "等待清晰突破和跟随", "或等到区间边缘"],
    entry: ["通常不入场", "只在明确突破后考虑", "高手可极小目标剥头皮"],
    stop: ["若交易，止损必须很小且接受频繁小亏"],
    target: ["小目标", "不要期待趋势"],
    traps: ["在中间追涨杀跌", "看到每根信号K都想做", "手续费把小利润吃掉"]
  },
  {
    id: "tight-bull-channel",
    title: "紧密多头通道",
    family: "通道",
    aliases: ["Tight Bull Channel"],
    winRate: "顺势60%左右",
    probScore: 60,
    importance: 90,
    difficulty: 3,
    diagram: "channel",
    source: "PAF 17 Tight Channels / HTT 43",
    summary: "多头持续控制，回调浅。第一批做空反转通常失败。",
    best: ["连续高低点抬高", "回调浅且没有强空头K", "收盘多在高位"],
    entry: ["回调买入", "H1/H2买入", "突破后小回调买"],
    stop: ["最近回调低点下方", "信号K下方"],
    target: ["通道线", "测量移动", "磁力位"],
    traps: ["过早猜顶", "看到价格高就空", "在高潮末端才追大仓"]
  },
  {
    id: "tight-bear-channel",
    title: "紧密空头通道",
    family: "通道",
    aliases: ["Tight Bear Channel"],
    winRate: "顺势60%左右",
    probScore: 60,
    importance: 90,
    difficulty: 3,
    diagram: "channel",
    source: "PAF 17 Tight Channels / HTT 44",
    summary: "空头持续控制，反弹浅。第一批做多反转通常失败。",
    best: ["连续高低点降低", "反弹浅且没有强多头K", "收盘多在低位"],
    entry: ["反弹卖出", "L1/L2卖出", "突破后小反弹卖"],
    stop: ["最近回调高点上方", "信号K上方"],
    target: ["通道线", "测量移动", "磁力位"],
    traps: ["过早猜底", "看到价格低就多", "在高潮末端才追大仓"]
  },
  {
    id: "broad-bull-channel",
    title: "宽幅多头通道",
    family: "通道",
    aliases: ["Broad Bull Channel"],
    winRate: "双向55%左右",
    probScore: 55,
    importance: 84,
    difficulty: 4,
    diagram: "channel",
    source: "PAF 16 Channels / HTT 45",
    summary: "仍是上涨倾向，但回调大、重叠多，更像带方向的交易区间。",
    best: ["上升通道但波段重叠", "低位买优于高位追", "上轨可止盈或轻仓反向"],
    entry: ["下轨或EMA附近买", "强空头失败后买", "上轨只做保守反向或止盈"],
    stop: ["通道低点下方", "失败突破极端外"],
    target: ["上轨", "前高", "区间式小目标"],
    traps: ["在上轨追多", "把它当强趋势持太久", "忽略下轨反弹"]
  },
  {
    id: "broad-bear-channel",
    title: "宽幅空头通道",
    family: "通道",
    aliases: ["Broad Bear Channel"],
    winRate: "双向55%左右",
    probScore: 55,
    importance: 84,
    difficulty: 4,
    diagram: "channel",
    source: "PAF 16 Channels / HTT 46",
    summary: "仍是下跌倾向，但反弹大、重叠多，更像带方向的交易区间。",
    best: ["下降通道但波段重叠", "高位卖优于低位追", "下轨可止盈或轻仓反向"],
    entry: ["上轨或EMA附近卖", "强多头失败后卖"],
    stop: ["通道高点上方", "失败突破极端外"],
    target: ["下轨", "前低", "区间式小目标"],
    traps: ["在下轨追空", "把它当强趋势持太久", "忽略上轨反转"]
  },
  {
    id: "spike-and-channel",
    title: "尖刺 + 通道趋势",
    family: "趋势",
    aliases: ["Spike and Channel"],
    winRate: "顺势55-60%",
    probScore: 58,
    importance: 86,
    difficulty: 3,
    diagram: "cycle",
    source: "PAF 12 Market Cycle / PAF 14 Trends",
    summary: "强突破尖刺后进入较弱通道，是 Brooks 市场周期的核心结构。",
    best: ["先有强尖刺", "之后通道推进但开始重叠", "第一次反转多只是回调"],
    entry: ["尖刺后第一次回调顺势", "通道低买/高卖取决于方向", "通道末端降低顺势预期"],
    stop: ["回调极端外", "通道结构外"],
    target: ["测量尖刺", "通道线", "磁力位"],
    traps: ["尖刺后立刻逆势", "通道末端还按强趋势追", "看不出周期从突破转通道"]
  },
  {
    id: "small-pullback-trend",
    title: "小回调趋势",
    family: "趋势",
    aliases: ["Small Pullback Trend"],
    winRate: "顺势60%左右",
    probScore: 61,
    importance: 82,
    difficulty: 3,
    diagram: "trend",
    source: "PAF 14 Trends / HTT 40 Entering Late in Trends",
    summary: "趋势持续强，回调都很小，错过早期入场后容易越等越远。",
    best: ["连续趋势K", "回调很浅", "大多数反向信号无跟随"],
    entry: ["小回调顺势", "突破微型整理后顺势", "迟到者用小仓位和更宽计划"],
    stop: ["最近小回调外", "结构止损过远时减仓"],
    target: ["测量移动", "趋势通道线"],
    traps: ["觉得太高/太低就逆势", "等深回调等不到", "迟到后重仓追"]
  },
  {
    id: "micro-channel",
    title: "微型通道",
    family: "趋势",
    aliases: ["Micro Channel"],
    winRate: "顺势58-62%",
    probScore: 59,
    importance: 72,
    difficulty: 3,
    diagram: "trend",
    source: "PAF 14 Trends / PAF 17 Tight Channels",
    summary: "连续几根K线没有明显回调，低点或高点单向推进。它常代表短线趋势很强。",
    best: ["连续3-5根以上同方向推进", "收盘靠近极端", "逆势K没有突破前一根"],
    entry: ["第一次回调顺势", "突破微型通道后等待回踩"],
    stop: ["微型通道另一侧", "第一回调极端外"],
    target: ["小测量移动", "磁力位"],
    traps: ["微型通道末端追", "把回调当反转", "止损过小被正常回调扫掉"]
  },
  {
    id: "trend-from-the-open",
    title: "开盘趋势日",
    family: "开盘",
    aliases: ["Trend from the Open", "TFO"],
    winRate: "顺势60%+",
    probScore: 62,
    importance: 90,
    difficulty: 4,
    diagram: "opening",
    source: "HTT 48 Trading the Open",
    summary: "开盘后快速选择方向并持续推进，逆势尝试经常失败。",
    best: ["开盘强突破昨日高低点或重要磁力位", "早盘回调浅", "Always In 很早明确"],
    entry: ["早盘第一次回调顺势", "突破后回踩成功入场", "小回调趋势中小仓跟随"],
    stop: ["早盘结构外", "回调极端外"],
    target: ["日内测量移动", "昨日高低点", "尾盘磁力位"],
    traps: ["把趋势开盘当开盘反转", "错过早期后重仓追", "中午仍期待同样速度"]
  },
  {
    id: "opening-reversal",
    title: "开盘反转",
    family: "开盘",
    aliases: ["Opening Reversal", "OR"],
    winRate: "55-60%",
    probScore: 60,
    importance: 88,
    difficulty: 4,
    diagram: "opening",
    source: "HTT 48 Trading the Open / 10 Best Patterns",
    summary: "开盘快速测试关键价位失败后反向，可能形成当天主波段。",
    best: ["昨日高低点、缺口、开盘价或均线附近", "测试后无跟随", "反向K强并有后续"],
    entry: ["反向触发后入场", "保守者等突破微型趋势线"],
    stop: ["测试极端外", "信号K另一端"],
    target: ["开盘价", "昨日中点/高低点", "日内测量移动"],
    traps: ["强趋势开盘硬反转", "未到关键位提前猜", "第一根反向K太弱"]
  },
  {
    id: "failed-breakout-yesterday-high-low",
    title: "昨日高低点失败突破",
    family: "开盘",
    aliases: ["Failed YH/YL Breakout"],
    winRate: "55-60%",
    probScore: 58,
    importance: 78,
    difficulty: 4,
    diagram: "opening",
    source: "HTT 48 Trading the Open / PAF 19 Support and Resistance",
    summary: "日内交易常测试昨日高点或低点；突破失败会触发反向订单。",
    best: ["开盘或早盘快速测试昨日高低", "突破后回到昨日区间", "反向信号强"],
    entry: ["回到昨日区间后反向", "第二次失败后更稳"],
    stop: ["突破极端外", "信号K另一端"],
    target: ["开盘价", "昨日区间中线", "昨日另一端"],
    traps: ["突破有强跟随仍逆势", "目标太远", "忽略当日趋势背景"]
  },
  {
    id: "major-trend-reversal-top",
    title: "主要趋势反转顶部",
    family: "反转/MTR",
    aliases: ["MTR Top"],
    winRate: "约40%",
    probScore: 42,
    importance: 94,
    difficulty: 5,
    diagram: "mtr",
    source: "PAF 22 Major Trend Reversals / HTT 38",
    summary: "上涨趋势转空的早期尝试。胜率不高，但若成功，回报通常大于风险。",
    best: ["原上涨趋势清晰", "突破趋势线或通道", "回测前高失败并出现二次信号"],
    entry: ["第二次做空信号触发", "突破微型趋势线后做空"],
    stop: ["测试高点上方", "信号K上方"],
    target: ["至少两段下跌", "均线", "TBTL"],
    traps: ["第一次反转就重仓", "趋势线未破就猜顶", "回报空间不足"]
  },
  {
    id: "major-trend-reversal-bottom",
    title: "主要趋势反转底部",
    family: "反转/MTR",
    aliases: ["MTR Bottom"],
    winRate: "约40%",
    probScore: 42,
    importance: 94,
    difficulty: 5,
    diagram: "mtr",
    source: "PAF 22 Major Trend Reversals / HTT 39",
    summary: "下跌趋势转多的早期尝试。关键是结构变化，而不是单根反转K。",
    best: ["原下跌趋势清晰", "突破下降趋势线", "回测低点失败并出现二次信号"],
    entry: ["第二次做多信号触发", "突破微型趋势线后做多"],
    stop: ["测试低点下方", "信号K下方"],
    target: ["至少两段上涨", "均线", "TBTL"],
    traps: ["第一根大阳线就当反转", "空头仍强时抄底", "止损太远"]
  },
  {
    id: "higher-high-mtr",
    title: "更高高点 MTR",
    family: "反转/MTR",
    aliases: ["HH MTR"],
    winRate: "约40-45%",
    probScore: 44,
    importance: 76,
    difficulty: 5,
    diagram: "mtr",
    source: "PAF 22 / HTT 38",
    summary: "上涨趋势突破前高后失败，形成更高高点反转。常见于多头最后一次突破失败。",
    best: ["突破前高但无跟随", "突破趋势线后回测失败", "空头信号强"],
    entry: ["跌回前高下方后做空", "第二次空头信号更稳"],
    stop: ["新高上方", "信号K上方"],
    target: ["均线", "前一波低点", "两段下跌"],
    traps: ["强突破仍空", "没有二次信号", "只因价格创新高就卖"]
  },
  {
    id: "lower-low-mtr",
    title: "更低低点 MTR",
    family: "反转/MTR",
    aliases: ["LL MTR"],
    winRate: "约40-45%",
    probScore: 44,
    importance: 76,
    difficulty: 5,
    diagram: "mtr",
    source: "PAF 22 / HTT 39",
    summary: "下跌趋势跌破前低后失败，形成更低低点反转。常见于空头最后一次突破失败。",
    best: ["跌破前低但无跟随", "突破趋势线后回测失败", "多头信号强"],
    entry: ["回到前低上方后做多", "第二次多头信号更稳"],
    stop: ["新低下方", "信号K下方"],
    target: ["均线", "前一波高点", "两段上涨"],
    traps: ["强跌破仍抄底", "没有二次信号", "只因价格创新低就买"]
  },
  {
    id: "lower-high-mtr",
    title: "更低高点 MTR",
    family: "反转/MTR",
    aliases: ["LH MTR"],
    winRate: "45%左右",
    probScore: 45,
    importance: 72,
    difficulty: 4,
    diagram: "mtr",
    source: "PAF 22 Reversal Variants",
    summary: "上涨趋势线被破后，反弹无法回到前高，形成更低高点并转空。",
    best: ["趋势线已经被有效跌破", "反弹弱，形成更低高点", "空头信号在阻力附近出现"],
    entry: ["更低高点空头信号触发", "跌破小颈线后卖出"],
    stop: ["更低高点上方"],
    target: ["前低", "两段下跌", "区间下沿"],
    traps: ["趋势线没破就卖", "反弹其实强突破", "支撑太近"]
  },
  {
    id: "higher-low-mtr",
    title: "更高低点 MTR",
    family: "反转/MTR",
    aliases: ["HL MTR"],
    winRate: "45%左右",
    probScore: 45,
    importance: 72,
    difficulty: 4,
    diagram: "mtr",
    source: "PAF 22 Reversal Variants",
    summary: "下跌趋势线被破后，回调无法跌破前低，形成更高低点并转多。",
    best: ["趋势线已经被有效突破", "回调弱，形成更高低点", "多头信号在支撑附近出现"],
    entry: ["更高低点多头信号触发", "突破小颈线后买入"],
    stop: ["更高低点下方"],
    target: ["前高", "两段上涨", "区间上沿"],
    traps: ["趋势线没破就买", "回调其实强跌破", "阻力太近"]
  },
  {
    id: "wedge-top",
    title: "楔形顶部",
    family: "楔形",
    aliases: ["Wedge Top", "Three Pushes Up"],
    winRate: "40-50%",
    probScore: 48,
    importance: 86,
    difficulty: 4,
    diagram: "wedge",
    source: "PAF 24 Wedges",
    summary: "三次上推后动能衰减。它常带来两段回调，但不保证大反转。",
    best: ["第三推接近通道线或磁力位", "第三推收盘变弱", "出现空头信号或突破微型趋势线"],
    entry: ["第三推失败后试空", "跌破微型趋势线后试空"],
    stop: ["第三推高点上方"],
    target: ["均线", "两段回调", "前一推低点"],
    traps: ["强趋势里过早猜顶", "只数三推不看位置", "把回调当大反转"]
  },
  {
    id: "wedge-bottom",
    title: "楔形底部",
    family: "楔形",
    aliases: ["Wedge Bottom", "Three Pushes Down"],
    winRate: "40-50%",
    probScore: 48,
    importance: 86,
    difficulty: 4,
    diagram: "wedge",
    source: "PAF 24 Wedges",
    summary: "三次下推后动能衰减。它常带来两段反弹，但不保证大反转。",
    best: ["第三推接近通道线或支撑", "第三推收盘变弱", "出现多头信号或突破微型趋势线"],
    entry: ["第三推失败后试多", "突破微型趋势线后试多"],
    stop: ["第三推低点下方"],
    target: ["均线", "两段反弹", "前一推高点"],
    traps: ["强空头趋势里抄底", "只数三推不看位置", "把反弹当新牛市"]
  },
  {
    id: "parabolic-wedge",
    title: "抛物线楔形",
    family: "楔形",
    aliases: ["Parabolic Wedge"],
    winRate: "40-50%",
    probScore: 46,
    importance: 78,
    difficulty: 5,
    diagram: "wedge",
    source: "PAF 24 Wedges / PAF 29 Climaxes",
    summary: "推进越来越急的三推，通常带有高潮性质。失败后回调可能很快。",
    best: ["三推加速", "远离均线", "第三推附近出现强反向K"],
    entry: ["失败后反向试单", "保守者等第二次信号"],
    stop: ["极端点外"],
    target: ["均线", "两段回调", "前一加速起点"],
    traps: ["加速中提前挡车", "没有反向跟随", "止损太远但仓位不降"]
  },
  {
    id: "nested-wedge",
    title: "嵌套楔形",
    family: "楔形",
    aliases: ["Nested Wedge"],
    winRate: "45-55%",
    probScore: 52,
    importance: 66,
    difficulty: 5,
    diagram: "wedge",
    source: "PAF 24 Wedges",
    summary: "大三推中的第三推内部又形成小三推，代表末端结构更成熟。",
    best: ["接近强磁力位", "大三推和小三推共振", "小三推失败后有强反向K"],
    entry: ["小三推失败后入场", "第二次信号更稳"],
    stop: ["嵌套极端外"],
    target: ["均线", "大结构两段回调"],
    traps: ["复杂到看什么都像楔形", "背景仍是强趋势", "入场太早"]
  },
  {
    id: "final-flag",
    title: "末端旗形",
    family: "末端旗形",
    aliases: ["Final Flag"],
    winRate: "约40%",
    probScore: 42,
    importance: 84,
    difficulty: 5,
    diagram: "finalflag",
    source: "PAF 23 Final Flags / 10 Best Patterns",
    summary: "趋势末端的小整理先看起来像继续形态；当继续失败时，常形成反向波段。",
    best: ["趋势已经运行很久", "接近磁力位或测量目标", "旗形突破失败并反向"],
    entry: ["继续突破失败后反向", "跌/突破旗形另一侧后入场"],
    stop: ["旗形极端外", "失败突破极端外"],
    target: ["均线", "两段回调", "原趋势最后一段起点"],
    traps: ["趋势中段误判末端", "没有失败就逆势", "胜率低却仓位过大"]
  },
  {
    id: "double-top",
    title: "双顶",
    family: "双顶双底",
    aliases: ["Double Top", "DT"],
    winRate: "50-58%",
    probScore: 55,
    importance: 82,
    difficulty: 3,
    diagram: "range",
    source: "PAF 25 Double Tops and Bottoms",
    summary: "价格两次测试同一区域失败。它可以是区间反转，也可以是主要趋势反转的一部分。",
    best: ["第二次测试无跟随", "位置在区间高位或趋势末端", "跌破颈线或有空头信号"],
    entry: ["第二顶失败后做空", "跌破颈线后做空"],
    stop: ["第二顶上方"],
    target: ["颈线", "区间中线", "测量高度"],
    traps: ["强趋势中第一个双顶太早", "第二顶直接强突破", "下方支撑太近"]
  },
  {
    id: "double-bottom",
    title: "双底",
    family: "双顶双底",
    aliases: ["Double Bottom", "DB"],
    winRate: "50-58%",
    probScore: 55,
    importance: 82,
    difficulty: 3,
    diagram: "range",
    source: "PAF 25 Double Tops and Bottoms",
    summary: "价格两次测试同一区域失败。它可以是区间反转，也可以是主要趋势反转的一部分。",
    best: ["第二次测试无跟随", "位置在区间低位或趋势末端", "突破颈线或有多头信号"],
    entry: ["第二底失败后做多", "突破颈线后做多"],
    stop: ["第二底下方"],
    target: ["颈线", "区间中线", "测量高度"],
    traps: ["强空头中第一个双底太早", "第二底直接强跌破", "上方阻力太近"]
  },
  {
    id: "double-top-bear-flag",
    title: "双顶空头旗",
    family: "双顶双底",
    aliases: ["DT Bear Flag"],
    winRate: "55-60%",
    probScore: 58,
    importance: 78,
    difficulty: 3,
    diagram: "range",
    source: "PAF 25 / PAF 14 Trends",
    summary: "下跌趋势中的两次反弹失败，是空头趋势延续形态。",
    best: ["背景为空头趋势", "两次反弹到相近阻力", "第二顶失败后有空头信号"],
    entry: ["第二顶失败后卖出", "跌破小颈线后卖出"],
    stop: ["第二顶上方"],
    target: ["前低", "测量移动"],
    traps: ["背景已转交易区间", "第二顶强突破", "前低太近"]
  },
  {
    id: "double-bottom-bull-flag",
    title: "双底多头旗",
    family: "双顶双底",
    aliases: ["DB Bull Flag"],
    winRate: "55-60%",
    probScore: 58,
    importance: 78,
    difficulty: 3,
    diagram: "range",
    source: "PAF 25 / PAF 14 Trends",
    summary: "上涨趋势中的两次回调失败，是多头趋势延续形态。",
    best: ["背景为多头趋势", "两次回调到相近支撑", "第二底失败后有多头信号"],
    entry: ["第二底失败后买入", "突破小颈线后买入"],
    stop: ["第二底下方"],
    target: ["前高", "测量移动"],
    traps: ["背景已转交易区间", "第二底强跌破", "前高太近"]
  },
  {
    id: "triangle",
    title: "三角形",
    family: "三角形",
    aliases: ["Triangle"],
    winRate: "突破后看跟随",
    probScore: 52,
    importance: 76,
    difficulty: 4,
    diagram: "range",
    source: "PAF 26 Triangles",
    summary: "高低点收敛，市场进入突破模式。真正的交易优势来自突破方向和跟随。",
    best: ["波动逐渐收缩", "高低点收敛", "突破后有强收盘"],
    entry: ["突破三角形后顺势", "突破回踩成功后入场"],
    stop: ["三角形另一侧", "回踩结构外"],
    target: ["三角形高度测量移动", "下一个磁力位"],
    traps: ["三角形内部来回交易", "假突破追单", "突破前预判方向"]
  },
  {
    id: "expanding-triangle",
    title: "扩大型三角形",
    family: "三角形",
    aliases: ["Expanding Triangle"],
    winRate: "50-55%",
    probScore: 52,
    importance: 68,
    difficulty: 5,
    diagram: "range",
    source: "PAF 26 Triangles",
    summary: "高点和低点都扩大，情绪更混乱。通常适合边缘交易，不适合中间追单。",
    best: ["不断突破前高和前低但缺乏跟随", "两边都被套", "边缘出现失败突破"],
    entry: ["新高失败后卖", "新低失败后买", "等待强反向K"],
    stop: ["失败突破极端外"],
    target: ["中线", "对侧边缘"],
    traps: ["中间交易", "把每次突破当趋势", "止损太小"]
  },
  {
    id: "head-and-shoulders-top",
    title: "头肩顶",
    family: "头肩",
    aliases: ["Head and Shoulders Top", "H&S Top"],
    winRate: "45-55%",
    probScore: 52,
    importance: 70,
    difficulty: 4,
    diagram: "mtr",
    source: "PAF 27 Head and Shoulders",
    summary: "本质是MTR的一种视觉形式：左肩、头部、右肩分别代表趋势减弱和测试失败。",
    best: ["上涨趋势末端", "头部突破失败", "右肩形成更低高点"],
    entry: ["右肩空头信号", "跌破颈线后空"],
    stop: ["右肩或头部上方"],
    target: ["颈线测量", "两段下跌"],
    traps: ["强趋势中太早画头肩", "颈线附近追空空间不足", "只看形状不看行为"]
  },
  {
    id: "head-and-shoulders-bottom",
    title: "头肩底",
    family: "头肩",
    aliases: ["Head and Shoulders Bottom", "Inverse H&S"],
    winRate: "45-55%",
    probScore: 52,
    importance: 70,
    difficulty: 4,
    diagram: "mtr",
    source: "PAF 27 Head and Shoulders",
    summary: "本质是MTR底部的一种视觉形式：空头趋势减弱，右肩形成更高低点。",
    best: ["下跌趋势末端", "头部跌破失败", "右肩形成更高低点"],
    entry: ["右肩多头信号", "突破颈线后多"],
    stop: ["右肩或头部下方"],
    target: ["颈线测量", "两段上涨"],
    traps: ["强空头中太早画头肩", "颈线附近追多空间不足", "只看形状不看行为"]
  },
  {
    id: "rounded-top",
    title: "圆弧顶",
    family: "圆弧",
    aliases: ["Rounded Top"],
    winRate: "45-55%",
    probScore: 50,
    importance: 58,
    difficulty: 4,
    diagram: "mtr",
    source: "PAF 28 Rounded Tops and Bottoms",
    summary: "上涨动能逐渐减弱，价格从趋势慢慢转成区间再转空。它往往比尖锐反转更慢。",
    best: ["高点抬升越来越弱", "重叠和尾巴增加", "下破小区间后跟随"],
    entry: ["跌破圆弧内小区间后空", "反弹形成更低高点后空"],
    stop: ["最近摆动高点上方"],
    target: ["区间下沿", "测量移动"],
    traps: ["太早卖在圆弧初期", "震荡时间长导致成本高", "忽略突然强突破恢复趋势"]
  },
  {
    id: "rounded-bottom",
    title: "圆弧底",
    family: "圆弧",
    aliases: ["Rounded Bottom"],
    winRate: "45-55%",
    probScore: 50,
    importance: 58,
    difficulty: 4,
    diagram: "mtr",
    source: "PAF 28 Rounded Tops and Bottoms",
    summary: "下跌动能逐渐减弱，价格从趋势慢慢转成区间再转多。",
    best: ["低点降低越来越弱", "重叠和尾巴增加", "上破小区间后跟随"],
    entry: ["突破圆弧内小区间后多", "回调形成更高低点后多"],
    stop: ["最近摆动低点下方"],
    target: ["区间上沿", "测量移动"],
    traps: ["太早买在圆弧初期", "震荡时间长导致成本高", "忽略突然强跌破恢复趋势"]
  },
  {
    id: "climactic-reversal",
    title: "高潮反转",
    family: "高潮",
    aliases: ["Climactic Reversal"],
    winRate: "40-50%",
    probScore: 47,
    importance: 88,
    difficulty: 5,
    diagram: "climax",
    source: "PAF 29 Climaxes / HTT 42",
    summary: "短时间过度推进后，趋势方获利了结，反向方试图制造两段回调。",
    best: ["连续大K、远离均线", "接近测量目标或重要磁力位", "出现强反向K和跟随"],
    entry: ["不抢第一根；等失败继续或二次信号", "突破微型趋势线后反向"],
    stop: ["高潮极端外"],
    target: ["均线", "两段回调", "高潮起点附近"],
    traps: ["趋势可以继续高潮", "止损很远但仓位不降", "把所有大K都当高潮"]
  },
  {
    id: "exhaustion-gap",
    title: "衰竭缺口",
    family: "缺口",
    aliases: ["Exhaustion Gap"],
    winRate: "40-50%",
    probScore: 46,
    importance: 68,
    difficulty: 5,
    diagram: "climax",
    source: "PAF 11 Gaps / PAF 29 Climaxes",
    summary: "趋势末端的缺口看起来很强，但若快速回补，可能说明最后一批追单者被困。",
    best: ["趋势已经过度延伸", "缺口后无跟随", "快速回补并反向收盘"],
    entry: ["缺口回补后反向", "第二次反向信号更稳"],
    stop: ["缺口极端外"],
    target: ["均线", "前一整理区", "两段回调"],
    traps: ["把中段测量缺口误当衰竭", "缺口未回补就抢反向", "波动过大"]
  },
  {
    id: "trend-channel-line-overshoot",
    title: "通道线过冲反转",
    family: "通道",
    aliases: ["TCL Overshoot and Reversal"],
    winRate: "45-55%",
    probScore: 52,
    importance: 76,
    difficulty: 4,
    diagram: "channel",
    source: "PAF 16 Channels / PAF 21 Reversals",
    summary: "价格冲出通道线后失败，常说明趋势进入过度状态，至少可能回到均线或通道中线。",
    best: ["通道已持续一段时间", "过冲发生在第三次触及附近", "过冲后出现反向信号"],
    entry: ["过冲失败后反向", "等回到通道内后入场"],
    stop: ["过冲极端外"],
    target: ["均线", "通道中线", "另一侧通道线"],
    traps: ["强突破通道线仍反向", "第一次触线就做反转", "忽略趋势背景"]
  },
  {
    id: "failed-final-flag-breakout",
    title: "末端旗形突破失败",
    family: "末端旗形",
    aliases: ["Failed FF BO"],
    winRate: "40-50%",
    probScore: 46,
    importance: 76,
    difficulty: 5,
    diagram: "finalflag",
    source: "PAF 23 Final Flags",
    summary: "末端旗形真正的触发常是继续突破失败；失败越快，套牢盘越明显。",
    best: ["趋势末端小整理", "继续突破无跟随", "快速反向穿回旗形"],
    entry: ["回到旗形内后反向", "突破旗形另一侧后入场"],
    stop: ["失败突破极端外"],
    target: ["均线", "两段回调", "原趋势最后腿起点"],
    traps: ["旗形突破成功仍反向", "趋势中段误判", "胜率低却不控制仓位"]
  },
  {
    id: "measured-move",
    title: "测量移动",
    family: "目标/磁力",
    aliases: ["Measured Move", "MM"],
    winRate: "目标框架",
    probScore: 55,
    importance: 94,
    difficulty: 3,
    diagram: "measured",
    source: "PAF 20 Measured Moves / 10 Best Patterns",
    summary: "测量移动不是入场形态，而是目标、磁力位和交易者方程的核心工具。",
    best: ["第一段运动清晰", "中间有明确回调或区间", "第二段启动后有跟随"],
    entry: ["与突破、回调或反转触发配合", "不要只因有测量目标入场"],
    stop: ["按实际入场形态设置"],
    target: ["Leg1=Leg2", "区间高度投射", "缺口或突破点投射"],
    traps: ["把目标当入场理由", "目标太近仍开仓", "目标位附近追单"]
  },
  {
    id: "magnet-test-reversal",
    title: "磁力位测试反转",
    family: "目标/磁力",
    aliases: ["Magnet Test", "Support/Resistance Test"],
    winRate: "条件增强",
    probScore: 55,
    importance: 90,
    difficulty: 3,
    diagram: "magnets",
    source: "PAF 19 Support and Resistance / 10 Best Patterns",
    summary: "前高低、开盘价、均线、趋势线、测量目标都会吸引价格。交易信号来自到位后的反应。",
    best: ["磁力位明显且多数人可见", "到位后出现失败突破或强反向K", "与形态共振"],
    entry: ["磁力位附近等待触发", "失败突破后反向", "突破回踩成功后顺势"],
    stop: ["磁力位失败极端外", "信号K另一端"],
    target: ["下一个磁力位", "区间中线/另一侧"],
    traps: ["一到位就交易", "画太多线", "突破成功仍反向"]
  },
  {
    id: "ema-gap-bar",
    title: "均线缺口K",
    family: "目标/磁力",
    aliases: ["Moving Average Gap Bar", "MGB"],
    winRate: "45-55%",
    probScore: 52,
    importance: 58,
    difficulty: 4,
    diagram: "magnets",
    source: "PAF 14 Trends / PAF 19 Support and Resistance",
    summary: "强趋势远离均线后，第一根触及或接近均线的K线常成为测试点，可能引发反转或恢复趋势。",
    best: ["强趋势远离EMA", "首次回到EMA附近", "测试后出现清晰信号"],
    entry: ["顺趋势恢复信号", "若趋势末端则等反向二次信号"],
    stop: ["测试K另一端", "回调结构外"],
    target: ["前高/前低", "均线反弹目标", "两段运动"],
    traps: ["把EMA当魔法线", "没有信号就交易", "忽略市场周期"]
  },
  {
    id: "second-entry",
    title: "第二次入场",
    family: "入场逻辑",
    aliases: ["Second Entry", "二次信号"],
    winRate: "通常高于第一次",
    probScore: 58,
    importance: 92,
    difficulty: 3,
    diagram: "h2l2",
    source: "PAF 09 / PAF 21 Reversals / PAF 22 MTR",
    summary: "很多 Brooks 形态都强调第二次尝试：第一次失败暴露对手方，第二次触发更有信息量。",
    best: ["第一次信号失败或只小幅运动", "第二次在更好位置出现", "背景支持该方向"],
    entry: ["第二次触发入场", "二次信号质量强时优先"],
    stop: ["第二次信号结构外"],
    target: ["按所在形态设置", "至少看1R或最近磁力位"],
    traps: ["所有第二次都做", "忽略背景", "第二次已远离好位置"]
  },
  {
    id: "failed-second-entry",
    title: "第二次入场失败",
    family: "失败形态",
    aliases: ["Failed H2", "Failed L2", "Failed Second Entry"],
    winRate: "55-60%",
    probScore: 58,
    importance: 76,
    difficulty: 4,
    diagram: "h2l2",
    source: "PAF 09 / PAF 15 / PAF 18",
    summary: "广受关注的第二次入场失败时，反向力量常很强，因为一批交易者被迫止损。",
    best: ["明显H2/L2触发后没有跟随", "快速反向穿回触发位", "背景支持反向"],
    entry: ["二次入场失败后反向", "跌/突破信号K另一端"],
    stop: ["失败触发极端外"],
    target: ["最近磁力位", "区间另一侧", "测量移动"],
    traps: ["原趋势仍强，失败只是小回调", "入场过晚", "反向空间不足"]
  },
  {
    id: "failed-major-reversal",
    title: "主要反转失败",
    family: "失败形态",
    aliases: ["Failed MTR"],
    winRate: "55-60%",
    probScore: 57,
    importance: 78,
    difficulty: 4,
    diagram: "mtr",
    source: "PAF 21 Reversals / PAF 22 MTR",
    summary: "MTR 失败常让市场回到原趋势方向。反转交易者止损会推动原趋势恢复。",
    best: ["反转信号触发后无跟随", "价格重新站回原趋势方向", "原趋势背景仍有惯性"],
    entry: ["反转失败后顺原趋势", "突破反转信号另一端入场"],
    stop: ["失败结构外"],
    target: ["前极端", "测量移动", "趋势恢复目标"],
    traps: ["原趋势已经真正结束", "失败不清晰就追", "目标太近"]
  },
  {
    id: "failed-wedge",
    title: "楔形失败",
    family: "失败形态",
    aliases: ["Failed Wedge"],
    winRate: "55-60%",
    probScore: 56,
    importance: 66,
    difficulty: 4,
    diagram: "wedge",
    source: "PAF 24 Wedges",
    summary: "大家看到三推想反转，但第三推后的反向没有跟随，市场恢复原方向。",
    best: ["楔形反转触发后失败", "价格重新突破第三推极端", "原趋势仍强"],
    entry: ["楔形反转失败后顺原趋势", "突破极端后等待回踩"],
    stop: ["失败结构外"],
    target: ["测量移动", "下一个磁力位"],
    traps: ["原趋势已经转区间", "突破极端后已到目标", "只因楔形失败就无脑追"]
  },
  {
    id: "climax-then-trading-range",
    title: "高潮后交易区间",
    family: "高潮",
    aliases: ["Climax to TR"],
    winRate: "常见路径",
    probScore: 54,
    importance: 82,
    difficulty: 3,
    diagram: "climax",
    source: "PAF 12 Market Cycle / PAF 29 Climaxes",
    summary: "高潮后不一定立刻反转，更常见的是进入横盘消化。交易方式要从趋势预期切换到区间预期。",
    best: ["高潮后开始重叠", "前进速度明显下降", "多次突破无跟随"],
    entry: ["区间边缘交易", "等待失败突破", "中间少做"],
    stop: ["区间边缘外"],
    target: ["中线", "另一侧", "小目标"],
    traps: ["高潮后立刻期待大反转", "仍按强趋势追", "区间中间频繁交易"]
  },
  {
    id: "late-trend-entry",
    title: "趋势后期入场",
    family: "趋势",
    aliases: ["Entering Late in Trends"],
    winRate: "看管理",
    probScore: 52,
    importance: 78,
    difficulty: 5,
    diagram: "trend",
    source: "HTT 40 Entering Late in Trends",
    summary: "错过趋势早期后仍可入场，但必须承认止损更远、回报空间更少、管理更难。",
    best: ["趋势仍强且没有明显反转证据", "有小回调或突破回踩", "下一个磁力位仍有空间"],
    entry: ["小仓位顺趋势", "等回调而不是追最远端"],
    stop: ["结构止损，不因迟到而缩到不合理"],
    target: ["较近磁力位", "小目标或部分止盈"],
    traps: ["后期重仓追", "目标太远", "看到利润回撤后情绪化"]
  },
  {
    id: "always-in-flip",
    title: "Always In 翻转",
    family: "趋势",
    aliases: ["AI Flip", "AIL/AIS Shift"],
    winRate: "方向过滤",
    probScore: 56,
    importance: 98,
    difficulty: 4,
    diagram: "cycle",
    source: "PAF 13 Always In",
    summary: "这不是单个图形，而是判断市场控制权的核心框架。许多形态只有顺 Always In 才有优势。",
    best: ["强突破改变控制权", "反向回调失败", "原方向信号连续失败"],
    entry: ["翻转确认后优先顺新方向", "等待第一次回调"],
    stop: ["翻转结构外", "最近反向极端外"],
    target: ["新方向测量移动", "下一个磁力位"],
    traps: ["每根K都改方向", "把小回调当翻转", "不结合市场周期"]
  },
  {
    id: "buy-vacuum-sell-vacuum",
    title: "买入/卖出真空到磁力位",
    family: "目标/磁力",
    aliases: ["Buy Vacuum", "Sell Vacuum"],
    winRate: "磁力现象",
    probScore: 50,
    importance: 64,
    difficulty: 4,
    diagram: "magnets",
    source: "PAF 19 Support and Resistance",
    summary: "价格快速被吸向明显磁力位，最后一段可能很急，但到位后容易出现获利了结。",
    best: ["上方/下方有明显目标", "中间阻力/支撑少", "价格加速靠近目标"],
    entry: ["通常不在目标前最后一段追", "到位后观察突破或失败"],
    stop: ["按触发形态设置"],
    target: ["磁力位本身", "到位后降低预期"],
    traps: ["目标前追进后立刻反转", "把真空当永久趋势", "无视目标位获利了结"]
  },
  {
    id: "reversal-after-breakout-test",
    title: "突破测试后的反转",
    family: "反转/MTR",
    aliases: ["Test After BO", "Failed Test"],
    winRate: "45-55%",
    probScore: 52,
    importance: 76,
    difficulty: 4,
    diagram: "mtr",
    source: "PAF 15 / PAF 21 Reversals",
    summary: "突破后回测原极端，如果测试失败并反向，常形成较好的反转或区间交易机会。",
    best: ["原突破已经走过一段", "回测前高/前低失败", "反向信号强"],
    entry: ["测试失败后反向", "第二次失败更稳"],
    stop: ["测试极端外"],
    target: ["区间中线", "均线", "前一波起点"],
    traps: ["突破仍强时逆势", "测试还没失败就抢", "目标空间不足"]
  },
  {
    id: "pullback-breaks-trendline",
    title: "回调突破趋势线",
    family: "趋势",
    aliases: ["Trendline Break PB"],
    winRate: "背景信号",
    probScore: 50,
    importance: 72,
    difficulty: 3,
    diagram: "mtr",
    source: "PAF 21 Reversals / PAF 22 MTR",
    summary: "趋势线被突破通常只是反转准备，不是立即反转。它告诉你趋势控制权开始松动。",
    best: ["之前趋势清晰", "趋势线被明显突破", "之后回测极端失败才有交易价值"],
    entry: ["不因趋势线破就直接反向", "等待测试失败或二次信号"],
    stop: ["测试极端外"],
    target: ["两段反向", "均线", "TBTL"],
    traps: ["趋势线一破就重仓反向", "画线过于主观", "忽略强趋势惯性"]
  },
  {
    id: "inside-bar-breakout",
    title: "内包K突破",
    family: "K线信号",
    aliases: ["Inside Bar BO", "ioi"],
    winRate: "50-58%",
    probScore: 54,
    importance: 62,
    difficulty: 3,
    diagram: "signal",
    source: "PAF 08 Candles Setups and Signal Bars",
    summary: "内包K代表短暂压缩。方向来自突破和背景，不来自内包K本身。",
    best: ["出现在强趋势小回调", "或出现在区间边缘", "突破后有跟随"],
    entry: ["突破内包K高/低点", "结合背景选择方向"],
    stop: ["母K另一端或信号K另一端"],
    target: ["最近磁力位", "小测量移动"],
    traps: ["区间中间双向挂单被来回扫", "内包K太大", "突破无跟随"]
  },
  {
    id: "outside-bar-signal",
    title: "外包K信号",
    family: "K线信号",
    aliases: ["Outside Bar", "Outside Down/Up"],
    winRate: "50-58%",
    probScore: 54,
    importance: 62,
    difficulty: 3,
    diagram: "signal",
    source: "PAF 08 Candles Setups and Signal Bars",
    summary: "外包K显示双方都试过方向，收盘位置决定信号质量。位置比形状更重要。",
    best: ["出现在关键价位", "收盘靠近突破方向极端", "下一根有跟随"],
    entry: ["按外包K收盘方向触发", "保守者等下一根确认"],
    stop: ["外包K另一端，通常较远", "风险过大时放弃"],
    target: ["最近磁力位", "区间另一侧"],
    traps: ["外包K过大导致风险收益差", "收盘在中间", "区间中间盲目追"]
  },
  {
    id: "signal-bar-at-key-level",
    title: "关键位信号K",
    family: "K线信号",
    aliases: ["Signal Bar at S/R"],
    winRate: "条件增强",
    probScore: 56,
    importance: 86,
    difficulty: 2,
    diagram: "signal",
    source: "PAF 08 / PAF 19",
    summary: "单根信号K只有在关键背景中才有意义。位置、收盘和后续入场K共同决定质量。",
    best: ["支撑阻力、区间边缘、趋势线、均线或测量目标附近", "信号K收盘强", "入场K有跟随"],
    entry: ["突破信号K高/低点", "若入场K弱则降低预期"],
    stop: ["信号K另一端", "关键位外侧"],
    target: ["最近磁力位", "1R以上", "区间中线/另一侧"],
    traps: ["只看K线形状", "位置在区间中间", "信号K过大"]
  },
  {
    id: "failed-signal-bar",
    title: "信号K失败",
    family: "失败形态",
    aliases: ["Failed Signal Bar"],
    winRate: "55%左右",
    probScore: 55,
    importance: 70,
    difficulty: 3,
    diagram: "signal",
    source: "PAF 08 / PAF 21",
    summary: "明显信号K触发后没有跟随，反向突破信号K另一端，常形成反向交易机会。",
    best: ["信号K本身吸引了很多入场", "触发后立刻反向", "反向背景更合理"],
    entry: ["信号K失败后反向入场", "突破信号K另一端"],
    stop: ["失败极端外"],
    target: ["最近磁力位", "区间另一侧"],
    traps: ["强趋势里的小失败", "反向空间不足", "失败不明显"]
  },
  {
    id: "scalp-in-trading-range",
    title: "区间剥头皮",
    family: "交易区间",
    aliases: ["TR Scalp"],
    winRate: "高手小优势",
    probScore: 52,
    importance: 60,
    difficulty: 5,
    diagram: "range",
    source: "PAF 31 Swing Trading and Scalping / HTT 47",
    summary: "区间里小目标交易可以频繁，但对执行、成本和速度要求高。",
    best: ["区间边界清晰", "手续费滑点低", "目标和止损都很小且明确"],
    entry: ["边缘反向", "失败突破后剥头皮"],
    stop: ["边缘外", "极小结构外"],
    target: ["小目标", "中线附近"],
    traps: ["新手在中间频繁做", "成本吃掉利润", "把剥头皮变成扛单"]
  },
  {
    id: "swing-after-strong-breakout",
    title: "强突破后的波段持有",
    family: "交易管理",
    aliases: ["Swing after BO"],
    winRate: "看跟随，60%+环境",
    probScore: 60,
    importance: 82,
    difficulty: 4,
    diagram: "breakout",
    source: "PAF 31 Swing Trading and Scalping / HTT 41",
    summary: "强突破不是只做小目标。若跟随好，Brooks 会考虑波段持有，让盈利覆盖小亏。",
    best: ["突破强且有跟随", "回调浅", "目标空间大"],
    entry: ["突破或回调入场后留部分仓位", "用结构保护止损"],
    stop: ["初始结构止损", "盈利后用更高低点保护"],
    target: ["测量移动", "TBTL", "尾盘磁力位"],
    traps: ["弱突破还硬波段", "盈利后过早平光", "不接受正常回调"]
  },
  {
    id: "scale-in-trading-range",
    title: "区间加仓摊位",
    family: "交易管理",
    aliases: ["Scaling In TR"],
    winRate: "高手策略",
    probScore: 50,
    importance: 62,
    difficulty: 5,
    diagram: "range",
    source: "PAF 35 Scaling In",
    summary: "Brooks 会讲加仓，但这是高级管理，不是亏损后随便补仓。只适合预先定义的区间环境。",
    best: ["明确交易区间", "仓位很小", "最坏风险已事先计算"],
    entry: ["边缘附近分批", "失败突破后改善均价"],
    stop: ["总风险止损", "区间真正突破后退出"],
    target: ["回到均价盈利", "中线", "另一侧"],
    traps: ["趋势日逆势加仓", "越亏越补", "没有最大风险上限"]
  }
];
